// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Channel struct {
	ID             string             `json:"id"`
	Name           pgtype.Text        `json:"name"`
	IsPrivate      bool               `json:"is_private"`
	IsArchived     bool               `json:"is_archived"`
	LastIngestedTs pgtype.Text        `json:"last_ingested_ts"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type IngestState struct {
	ChannelID       string             `json:"channel_id"`
	OldestTsFetched pgtype.Text        `json:"oldest_ts_fetched"`
	NewestTsFetched pgtype.Text        `json:"newest_ts_fetched"`
	BackfillDone    bool               `json:"backfill_done"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Message struct {
	ID        int64              `json:"id"`
	ChannelID string             `json:"channel_id"`
	SlackTs   string             `json:"slack_ts"`
	ThreadTs  pgtype.Text        `json:"thread_ts"`
	UserID    pgtype.Text        `json:"user_id"`
	Text      pgtype.Text        `json:"text"`
	RawJson   []byte             `json:"raw_json"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MessageEmbedding struct {
	MessageID int64              `json:"message_id"`
	Embedding pgvector.Vector    `json:"embedding"`
	Model     string             `json:"model"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MessageReaction struct {
	MessageID int64              `json:"message_id"`
	Emoji     string             `json:"emoji"`
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          string             `json:"id"`
	Name        pgtype.Text        `json:"name"`
	DisplayName pgtype.Text        `json:"display_name"`
	RealName    pgtype.Text        `json:"real_name"`
	IsBot       bool               `json:"is_bot"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
