// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const countMessagesNeedingEmbedding = `-- name: CountMessagesNeedingEmbedding :one
SELECT COUNT(*) FROM messages m
LEFT JOIN message_embeddings e ON m.id = e.message_id
WHERE m.deleted_at IS NULL
  AND m.text IS NOT NULL
  AND m.text != ''
  AND e.message_id IS NULL
`

func (q *Queries) CountMessagesNeedingEmbedding(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesNeedingEmbedding)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEmbedding = `-- name: DeleteEmbedding :exec
DELETE FROM message_embeddings WHERE message_id = $1
`

func (q *Queries) DeleteEmbedding(ctx context.Context, messageID int64) error {
	_, err := q.db.Exec(ctx, deleteEmbedding, messageID)
	return err
}

const deleteReaction = `-- name: DeleteReaction :exec
DELETE FROM message_reactions
WHERE message_id = $1 AND emoji = $2 AND user_id = $3
`

type DeleteReactionParams struct {
	MessageID int64  `json:"message_id"`
	Emoji     string `json:"emoji"`
	UserID    string `json:"user_id"`
}

func (q *Queries) DeleteReaction(ctx context.Context, arg DeleteReactionParams) error {
	_, err := q.db.Exec(ctx, deleteReaction, arg.MessageID, arg.Emoji, arg.UserID)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, is_private, is_archived, last_ingested_ts, created_at, updated_at FROM channels WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPrivate,
		&i.IsArchived,
		&i.LastIngestedTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIngestState = `-- name: GetIngestState :one
SELECT channel_id, oldest_ts_fetched, newest_ts_fetched, backfill_done, updated_at FROM ingest_state WHERE channel_id = $1
`

func (q *Queries) GetIngestState(ctx context.Context, channelID string) (IngestState, error) {
	row := q.db.QueryRow(ctx, getIngestState, channelID)
	var i IngestState
	err := row.Scan(
		&i.ChannelID,
		&i.OldestTsFetched,
		&i.NewestTsFetched,
		&i.BackfillDone,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, channel_id, slack_ts, thread_ts, user_id, text, raw_json, deleted_at, created_at, updated_at FROM messages WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SlackTs,
		&i.ThreadTs,
		&i.UserID,
		&i.Text,
		&i.RawJson,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageBySlackTS = `-- name: GetMessageBySlackTS :one
SELECT id, channel_id, slack_ts, thread_ts, user_id, text, raw_json, deleted_at, created_at, updated_at FROM messages WHERE channel_id = $1 AND slack_ts = $2
`

type GetMessageBySlackTSParams struct {
	ChannelID string `json:"channel_id"`
	SlackTs   string `json:"slack_ts"`
}

func (q *Queries) GetMessageBySlackTS(ctx context.Context, arg GetMessageBySlackTSParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageBySlackTS, arg.ChannelID, arg.SlackTs)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SlackTs,
		&i.ThreadTs,
		&i.UserID,
		&i.Text,
		&i.RawJson,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, display_name, real_name, is_bot, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.RealName,
		&i.IsBot,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEmbedding = `-- name: InsertEmbedding :exec
INSERT INTO message_embeddings (message_id, embedding, model)
VALUES ($1, $2, $3)
ON CONFLICT (message_id) DO UPDATE SET
    embedding = EXCLUDED.embedding,
    model = EXCLUDED.model,
    created_at = NOW()
`

type InsertEmbeddingParams struct {
	MessageID int64           `json:"message_id"`
	Embedding pgvector.Vector `json:"embedding"`
	Model     string          `json:"model"`
}

func (q *Queries) InsertEmbedding(ctx context.Context, arg InsertEmbeddingParams) error {
	_, err := q.db.Exec(ctx, insertEmbedding, arg.MessageID, arg.Embedding, arg.Model)
	return err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (channel_id, slack_ts, thread_ts, user_id, text, raw_json)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (channel_id, slack_ts) DO NOTHING
RETURNING id
`

type InsertMessageParams struct {
	ChannelID string      `json:"channel_id"`
	SlackTs   string      `json:"slack_ts"`
	ThreadTs  pgtype.Text `json:"thread_ts"`
	UserID    pgtype.Text `json:"user_id"`
	Text      pgtype.Text `json:"text"`
	RawJson   []byte      `json:"raw_json"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ChannelID,
		arg.SlackTs,
		arg.ThreadTs,
		arg.UserID,
		arg.Text,
		arg.RawJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, name, is_private, is_archived, last_ingested_ts, created_at, updated_at FROM channels WHERE is_archived = FALSE ORDER BY name
`

func (q *Queries) ListChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPrivate,
			&i.IsArchived,
			&i.LastIngestedTs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsNeedingBackfill = `-- name: ListChannelsNeedingBackfill :many
SELECT c.id, c.name, c.is_private, c.is_archived, c.last_ingested_ts, c.created_at, c.updated_at FROM channels c
LEFT JOIN ingest_state s ON c.id = s.channel_id
WHERE c.is_archived = FALSE AND (s.backfill_done IS NULL OR s.backfill_done = FALSE)
`

func (q *Queries) ListChannelsNeedingBackfill(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsNeedingBackfill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPrivate,
			&i.IsArchived,
			&i.LastIngestedTs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesNeedingEmbedding = `-- name: ListMessagesNeedingEmbedding :many
SELECT m.id, m.channel_id, m.slack_ts, m.text, m.thread_ts
FROM messages m
LEFT JOIN message_embeddings e ON m.id = e.message_id
WHERE m.deleted_at IS NULL
  AND m.text IS NOT NULL
  AND m.text != ''
  AND e.message_id IS NULL
ORDER BY m.created_at ASC
LIMIT $1
`

type ListMessagesNeedingEmbeddingRow struct {
	ID        int64       `json:"id"`
	ChannelID string      `json:"channel_id"`
	SlackTs   string      `json:"slack_ts"`
	Text      pgtype.Text `json:"text"`
	ThreadTs  pgtype.Text `json:"thread_ts"`
}

func (q *Queries) ListMessagesNeedingEmbedding(ctx context.Context, limit int32) ([]ListMessagesNeedingEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, listMessagesNeedingEmbedding, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesNeedingEmbeddingRow{}
	for rows.Next() {
		var i ListMessagesNeedingEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.SlackTs,
			&i.Text,
			&i.ThreadTs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMessage = `-- name: SoftDeleteMessage :exec
UPDATE messages SET deleted_at = NOW(), updated_at = NOW()
WHERE channel_id = $1 AND slack_ts = $2
`

type SoftDeleteMessageParams struct {
	ChannelID string `json:"channel_id"`
	SlackTs   string `json:"slack_ts"`
}

func (q *Queries) SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) error {
	_, err := q.db.Exec(ctx, softDeleteMessage, arg.ChannelID, arg.SlackTs)
	return err
}

const updateChannelLastIngestedTS = `-- name: UpdateChannelLastIngestedTS :exec
UPDATE channels SET last_ingested_ts = $2, updated_at = NOW() WHERE id = $1
`

type UpdateChannelLastIngestedTSParams struct {
	ID             string      `json:"id"`
	LastIngestedTs pgtype.Text `json:"last_ingested_ts"`
}

func (q *Queries) UpdateChannelLastIngestedTS(ctx context.Context, arg UpdateChannelLastIngestedTSParams) error {
	_, err := q.db.Exec(ctx, updateChannelLastIngestedTS, arg.ID, arg.LastIngestedTs)
	return err
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messages SET
    text = $3,
    raw_json = $4,
    updated_at = NOW()
WHERE channel_id = $1 AND slack_ts = $2
`

type UpdateMessageParams struct {
	ChannelID string      `json:"channel_id"`
	SlackTs   string      `json:"slack_ts"`
	Text      pgtype.Text `json:"text"`
	RawJson   []byte      `json:"raw_json"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.db.Exec(ctx, updateMessage,
		arg.ChannelID,
		arg.SlackTs,
		arg.Text,
		arg.RawJson,
	)
	return err
}

const upsertChannel = `-- name: UpsertChannel :exec
INSERT INTO channels (id, name, is_private, is_archived)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    is_private = EXCLUDED.is_private,
    is_archived = EXCLUDED.is_archived,
    updated_at = NOW()
`

type UpsertChannelParams struct {
	ID         string      `json:"id"`
	Name       pgtype.Text `json:"name"`
	IsPrivate  bool        `json:"is_private"`
	IsArchived bool        `json:"is_archived"`
}

func (q *Queries) UpsertChannel(ctx context.Context, arg UpsertChannelParams) error {
	_, err := q.db.Exec(ctx, upsertChannel,
		arg.ID,
		arg.Name,
		arg.IsPrivate,
		arg.IsArchived,
	)
	return err
}

const upsertIngestState = `-- name: UpsertIngestState :exec
INSERT INTO ingest_state (channel_id, oldest_ts_fetched, newest_ts_fetched, backfill_done)
VALUES ($1, $2, $3, $4)
ON CONFLICT (channel_id) DO UPDATE SET
    oldest_ts_fetched = COALESCE(EXCLUDED.oldest_ts_fetched, ingest_state.oldest_ts_fetched),
    newest_ts_fetched = COALESCE(EXCLUDED.newest_ts_fetched, ingest_state.newest_ts_fetched),
    backfill_done = EXCLUDED.backfill_done,
    updated_at = NOW()
`

type UpsertIngestStateParams struct {
	ChannelID       string      `json:"channel_id"`
	OldestTsFetched pgtype.Text `json:"oldest_ts_fetched"`
	NewestTsFetched pgtype.Text `json:"newest_ts_fetched"`
	BackfillDone    bool        `json:"backfill_done"`
}

func (q *Queries) UpsertIngestState(ctx context.Context, arg UpsertIngestStateParams) error {
	_, err := q.db.Exec(ctx, upsertIngestState,
		arg.ChannelID,
		arg.OldestTsFetched,
		arg.NewestTsFetched,
		arg.BackfillDone,
	)
	return err
}

const upsertReaction = `-- name: UpsertReaction :exec
INSERT INTO message_reactions (message_id, emoji, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (message_id, emoji, user_id) DO NOTHING
`

type UpsertReactionParams struct {
	MessageID int64  `json:"message_id"`
	Emoji     string `json:"emoji"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UpsertReaction(ctx context.Context, arg UpsertReactionParams) error {
	_, err := q.db.Exec(ctx, upsertReaction, arg.MessageID, arg.Emoji, arg.UserID)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, name, display_name, real_name, is_bot)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    display_name = EXCLUDED.display_name,
    real_name = EXCLUDED.real_name,
    is_bot = EXCLUDED.is_bot,
    updated_at = NOW()
`

type UpsertUserParams struct {
	ID          string      `json:"id"`
	Name        pgtype.Text `json:"name"`
	DisplayName pgtype.Text `json:"display_name"`
	RealName    pgtype.Text `json:"real_name"`
	IsBot       bool        `json:"is_bot"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser,
		arg.ID,
		arg.Name,
		arg.DisplayName,
		arg.RealName,
		arg.IsBot,
	)
	return err
}
